#!/bin/bash

# Script de démonstration du coverage
# Ce script montre comment utiliser le coverage de tests

echo "╔═══════════════════════════════════════════════════════════════╗"
echo "║           GUIDE RAPIDE - Test Coverage                       ║"
echo "╚═══════════════════════════════════════════════════════════════╝"
echo ""
echo "📚 Documentation disponible :"
echo "   • README_COVERAGE.md          - Guide complet (COMMENCEZ ICI ⭐)"
echo "   • TESTING_COVERAGE_GUIDE.md   - Documentation détaillée"
echo "   • NOUVEAUX_TESTS.md           - Détails des 76 tests ajoutés"
echo "   • QUICK_COMMANDS.md           - Aide-mémoire des commandes"
echo "   • RESUME_COVERAGE.md          - Résumé rapide"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🚀 ÉTAPES POUR LANCER LE COVERAGE :"
echo ""
echo "1️⃣  Installer les dépendances (première fois seulement)"
echo "    $ pip install -r code/requirements-dev.txt"
echo ""
echo "2️⃣  Lancer les tests avec coverage"
echo "    $ ./run_tests_with_coverage.sh"
echo ""
echo "3️⃣  Consulter le rapport HTML"
echo "    $ xdg-open htmlcov/index.html"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📊 EXEMPLE DE SORTIE :"
echo ""
echo "Name                                    Stmts   Miss  Cover   Missing"
echo "---------------------------------------------------------------------"
echo "src/geneweb/application/services.py      245     45    82%   12-15, 45-67"
echo "src/geneweb/infrastructure/repos.py       89     10    89%   23, 45-50"
echo "---------------------------------------------------------------------"
echo "TOTAL                                   1523    234    85%"
echo ""
echo "    Stmts  = Nombre total de lignes de code"
echo "    Miss   = Lignes NON testées"
echo "    Cover  = Pourcentage de couverture"
echo "    Missing = Numéros des lignes non testées"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🎯 OBJECTIFS DE COUVERTURE :"
echo ""
echo "    ✅ 70%+  = Minimum acceptable"
echo "    ✅ 80%+  = Bon"
echo "    ✅ 90%+  = Excellent"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "💡 COMMANDES UTILES :"
echo ""
echo "    # Lancer les tests avec coverage"
echo "    $ ./run_tests_with_coverage.sh"
echo ""
echo "    # Voir le rapport dans le terminal"
echo "    $ pytest --cov=src --cov=code"
echo ""
echo "    # Générer et ouvrir le rapport HTML"
echo "    $ pytest --cov=src --cov=code --cov-report=html"
echo "    $ xdg-open htmlcov/index.html"
echo ""
echo "    # Voir les détails d'un fichier spécifique"
echo "    $ coverage report --include='src/geneweb/application/services.py'"
echo ""
echo "    # Nettoyer les rapports"
echo "    $ rm -rf htmlcov .coverage coverage.xml"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📦 NOUVEAUX TESTS AJOUTÉS :"
echo ""
echo "    ✅ tests/application/test_date_utils.py            (24 tests)"
echo "    ✅ tests/infrastructure/test_sql_repositories.py   (19 tests)"
echo "    ✅ tests/presentation/test_formatters_advanced.py  (33 tests)"
echo ""
echo "    TOTAL : 76 nouveaux tests"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🎉 Pour commencer, lisez README_COVERAGE.md ou lancez :"
echo ""
echo "    $ ./run_tests_with_coverage.sh"
echo ""
echo "╚═══════════════════════════════════════════════════════════════╝"
