"""Manual migration for Genealogy and cascade deletes

Revision ID: 354afcc93d90
Revises: 931a1a52f0dc
Create Date: 2025-10-29 02:43:30.865522

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "354afcc93d90"
down_revision: Union[str, None] = "931a1a52f0dc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "genealogies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_genealogies_name"), "genealogies", ["name"], unique=False)

    with op.batch_alter_table("persons", schema=None) as batch_op:
        batch_op.add_column(sa.Column("genealogy_id", sa.Integer(), nullable=False))
        batch_op.create_foreign_key(
            "fk_persons_genealogy_id",
            "genealogies",
            ["genealogy_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.create_index(
            batch_op.f("ix_persons_genealogy_id"), ["genealogy_id"], unique=False
        )

    with op.batch_alter_table("families", schema=None) as batch_op:
        batch_op.add_column(sa.Column("genealogy_id", sa.Integer(), nullable=False))
        batch_op.create_foreign_key(
            "fk_families_genealogy_id",
            "genealogies",
            ["genealogy_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.create_index(
            batch_op.f("ix_families_genealogy_id"), ["genealogy_id"], unique=False
        )

    with op.batch_alter_table("places", schema=None) as batch_op:
        batch_op.add_column(sa.Column("genealogy_id", sa.Integer(), nullable=False))
        batch_op.create_foreign_key(
            "fk_places_genealogy_id",
            "genealogies",
            ["genealogy_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.create_index(
            batch_op.f("ix_places_genealogy_id"), ["genealogy_id"], unique=False
        )

    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.add_column(sa.Column("genealogy_id", sa.Integer(), nullable=False))
        batch_op.create_foreign_key(
            "fk_events_genealogy_id",
            "genealogies",
            ["genealogy_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.create_index(
            batch_op.f("ix_events_genealogy_id"), ["genealogy_id"], unique=False
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_events_genealogy_id"))
        batch_op.drop_constraint("fk_events_genealogy_id", type_="foreignkey")
        batch_op.drop_column("genealogy_id")

    with op.batch_alter_table("places", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_places_genealogy_id"))
        batch_op.drop_constraint("fk_places_genealogy_id", type_="foreignkey")
        batch_op.drop_column("genealogy_id")

    with op.batch_alter_table("families", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_families_genealogy_id"))
        batch_op.drop_constraint("fk_families_genealogy_id", type_="foreignkey")
        batch_op.drop_column("genealogy_id")

    with op.batch_alter_table("persons", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_persons_genealogy_id"))
        batch_op.drop_constraint("fk_persons_genealogy_id", type_="foreignkey")
        batch_op.drop_column("genealogy_id")

    op.drop_index(op.f("ix_genealogies_name"), table_name="genealogies")
    op.drop_table("genealogies")
    # ### end Alembic commands ###
